name: Terraform

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"

jobs:
  checks:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -diff

    - name: Terraform Security
      id: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        soft_fail: true

    - name: Teraform Lint
      id: tflint
      uses: devops-infra/action-tflint@v0.3
