kind: role
version: v5
metadata:
  name: k8s-developer
spec:
  allow:
    kubernetes_groups: ["system:masters"]
    kubernetes_labels:
      'env': ['dev', 'stage']
---
kind: role
version: v5
metadata:
  name: k8s-viewer
spec:
  allow:
    kubernetes_groups: ["teleport:readonly"]
    kubernetes_labels:
      '*': '*'
---
kind: role
version: v5
metadata:
  name: k8s-external-viewer
spec:
  allow:
    kubernetes_groups: ["teleport:customer"]
    kubernetes_labels:
      '*': '*'
---
kind: github
version: v3
metadata:
  name: github
spec:
  # client ID of your GitHub OAuth app
  client_id: ${teleport_github_client_id}
  # client secret of your GitHub OAuth app
  client_secret: ${teleport_github_client_secret}
  # This name will be shown on UI login screen
  display: GitHub
  # Change tele.example.com to your domain name
  redirect_url: https://${teleport_domain}:443/v1/webapi/github/callback
  # Map github teams to teleport roles
  teams_to_logins:
    - organization: ${teleport_github_org} # GitHub organization name
      team: admin            # GitHub team name within that organization
      # map GitHub's "admin" team to Teleport's "access" role
      logins: ["access", "editor", "k8s-viewer", "k8s-developer"]
    - organization: ${teleport_github_org} # GitHub organization name
      team: readonly
      logins: ["access", "k8s-external-viewer"]